-- Run in Supabase Dashboard → SQL Editor
-- Detects employees.id type and creates employee_loans with a matching employee_id FK.
-- Fixes: Could not find the table 'public.employee_loans' in the schema cache

-- Optional: inspect employees.id type first
-- SELECT column_name, data_type, udt_name
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'employees' AND column_name = 'id';

do $$
declare
  emp_udt text;
  emp_data_type text;
begin
  select c.udt_name, c.data_type
  into emp_udt, emp_data_type
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'employees'
    and c.column_name = 'id';

  if emp_udt is null then
    raise exception 'public.employees.id not found — create employees table first';
  end if;

  raise notice 'employees.id type: % (%)', emp_udt, emp_data_type;

  if emp_udt = 'uuid' then
    execute $sql$
      create table if not exists public.employee_loans (
        id uuid primary key default gen_random_uuid(),
        company_id bigint not null references public.companies (id) on delete cascade,
        employee_id uuid not null references public.employees (id) on delete cascade,
        amount numeric(12, 2) not null default 0,
        remaining_balance numeric(12, 2),
        monthly_deduction numeric(12, 2),
        total_amount numeric(12, 2),
        installments_total integer,
        installments_remaining integer,
        monthly_installment numeric(12, 2),
        start_date date,
        request_id bigint references public.requests (id) on delete set null,
        last_deducted_month text,
        status text not null default 'active'
          check (status in ('active', 'closed', 'completed', 'cancelled')),
        notes text,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
    $sql$;
  else
    execute $sql$
      create table if not exists public.employee_loans (
        id bigint generated by default as identity primary key,
        company_id bigint not null references public.companies (id) on delete cascade,
        employee_id bigint not null references public.employees (id) on delete cascade,
        amount numeric(12, 2) not null default 0,
        remaining_balance numeric(12, 2),
        monthly_deduction numeric(12, 2),
        total_amount numeric(12, 2),
        installments_total integer,
        installments_remaining integer,
        monthly_installment numeric(12, 2),
        start_date date,
        request_id bigint references public.requests (id) on delete set null,
        last_deducted_month text,
        status text not null default 'active'
          check (status in ('active', 'closed', 'completed', 'cancelled')),
        notes text,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
    $sql$;
  end if;
end $$;

alter table public.employee_loans
  add column if not exists company_id bigint references public.companies (id) on delete cascade,
  add column if not exists amount numeric(12, 2) not null default 0,
  add column if not exists remaining_balance numeric(12, 2),
  add column if not exists monthly_deduction numeric(12, 2),
  add column if not exists total_amount numeric(12, 2),
  add column if not exists installments_total integer,
  add column if not exists installments_remaining integer,
  add column if not exists monthly_installment numeric(12, 2),
  add column if not exists start_date date,
  add column if not exists request_id bigint references public.requests (id) on delete set null,
  add column if not exists last_deducted_month text,
  add column if not exists notes text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.payroll_records
  add column if not exists loan_deductions numeric not null default 0;

create index if not exists employee_loans_company_employee_idx
  on public.employee_loans (company_id, employee_id);

create index if not exists employee_loans_active_idx
  on public.employee_loans (company_id, status)
  where status = 'active';

create index if not exists employee_loans_request_id_idx
  on public.employee_loans (request_id)
  where request_id is not null;

alter table public.employee_loans enable row level security;

drop policy if exists employee_loans_company_all on public.employee_loans;
drop policy if exists "Tenant isolation" on public.employee_loans;
drop policy if exists employee_loans_select on public.employee_loans;
drop policy if exists employee_loans_manage on public.employee_loans;

create policy employee_loans_select
  on public.employee_loans for select to authenticated
  using (
    company_id = public.get_my_company_id()
    and (
      public.is_hr_staff()
      or public.is_company_manager()
      or exists (
        select 1
        from public.employees e
        where e.id = employee_loans.employee_id
          and e.auth_user_id = auth.uid()
      )
    )
  );

create policy employee_loans_manage
  on public.employee_loans for all to authenticated
  using (
    company_id = public.get_my_company_id()
    and (public.is_hr_staff() or public.is_company_manager())
  )
  with check (
    company_id = public.get_my_company_id()
    and (public.is_hr_staff() or public.is_company_manager())
  );

grant all on table public.employee_loans to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

notify pgrst, 'reload schema';
