-- Exeer core schema (run in Supabase SQL Editor if migrations are not linked)

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  full_name text not null,
  email text,
  phone_number text,
  gender text default 'ذكر',
  date_of_birth date,
  nationality text,
  id_number bigint,
  is_saudi boolean not null default false,
  address text,
  national_address text,
  image text,
  employee_number text,
  hire_date date,
  contract_type text default 'دوام كامل',
  contract_expiry date,
  employment_status text default 'نشط',
  role text default 'موظف',
  direct_manager_name text,
  job_title_name text,
  work_location_name text,
  department text,
  basic_salary numeric not null default 0,
  housing_allowance numeric not null default 0,
  other_allowance numeric not null default 0,
  iban text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  title text,
  description text not null,
  assigned_to_id bigint references public.employees (id) on delete set null,
  assigned_to_name text,
  deadline date,
  status text not null default 'قيد الانتظار',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  name text not null,
  description text,
  event_datetime timestamptz,
  location text,
  created_at timestamptz not null default now()
);

create table if not exists public.pending_requests (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  employee_name text not null,
  request_type text not null default 'طلب',
  description text,
  notes text,
  status text not null default 'معلق',
  created_at timestamptz not null default now()
);

create table if not exists public.payroll_records (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  employee_name text not null,
  month int not null,
  year int not null,
  basic_salary numeric not null default 0,
  housing_allowance numeric not null default 0,
  allowances numeric not null default 0,
  commissions numeric not null default 0,
  additional numeric not null default 0,
  penalties numeric not null default 0,
  gosi numeric not null default 0,
  delays numeric not null default 0,
  net numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.hr_job_archives (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  job_title text not null,
  ai_content text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists employees_company_id_idx on public.employees (company_id);
create index if not exists tasks_company_id_idx on public.tasks (company_id);
create index if not exists events_company_id_idx on public.events (company_id);
create index if not exists pending_requests_company_id_idx on public.pending_requests (company_id);
create index if not exists payroll_records_company_month_idx on public.payroll_records (company_id, year, month);
create index if not exists hr_job_archives_company_id_idx on public.hr_job_archives (company_id);

alter table public.companies enable row level security;
alter table public.employees enable row level security;
alter table public.tasks enable row level security;
alter table public.events enable row level security;
alter table public.pending_requests enable row level security;
alter table public.payroll_records enable row level security;
alter table public.hr_job_archives enable row level security;

-- Development-friendly policies (tighten with auth.uid() / company claims in production)
do $$
declare
  t text;
begin
  foreach t in array array[
    'companies','employees','tasks','events','pending_requests','payroll_records','hr_job_archives'
  ]
  loop
    execute format('drop policy if exists exeer_all_select on public.%I', t);
    execute format('drop policy if exists exeer_all_insert on public.%I', t);
    execute format('drop policy if exists exeer_all_update on public.%I', t);
    execute format('drop policy if exists exeer_all_delete on public.%I', t);
    execute format(
      'create policy exeer_all_select on public.%I for select using (true)',
      t
    );
    execute format(
      'create policy exeer_all_insert on public.%I for insert with check (true)',
      t
    );
    execute format(
      'create policy exeer_all_update on public.%I for update using (true)',
      t
    );
    execute format(
      'create policy exeer_all_delete on public.%I for delete using (true)',
      t
    );
  end loop;
end $$;

-- Optional seed (safe to re-run)
insert into public.companies (id, name)
overriding system value
values (118, 'Exeer Demo')
on conflict (id) do update set name = excluded.name;

select setval(
  pg_get_serial_sequence('public.companies', 'id'),
  greatest((select coalesce(max(id), 1) from public.companies), 118)
);

insert into public.employees (
  company_id, full_name, email, phone_number, employee_number, department,
  employment_status, role, basic_salary, housing_allowance
)
select 118, v.full_name, v.email, v.phone, v.emp_no, v.dept, 'نشط', 'موظف', v.basic, v.housing
from (
  values
    ('أحمد العتيبي', 'ahmed@exeer.sa', '0500000001', 'EMP-001', 'الموارد البشرية', 12000::numeric, 3000::numeric),
    ('فاطمة الشمري', 'fatima@exeer.sa', '0500000002', 'EMP-002', 'المالية', 11000::numeric, 2500::numeric),
    ('خالد القحطاني', 'khalid@exeer.sa', '0500000003', 'EMP-003', 'التقنية', 13000::numeric, 3000::numeric)
) as v(full_name, email, phone, emp_no, dept, basic, housing)
where not exists (
  select 1 from public.employees e where e.company_id = 118 and e.employee_number = v.emp_no
);

insert into public.pending_requests (company_id, employee_name, request_type, description, status)
select 118, 'أحمد العتيبي', 'إجازة سنوية', 'طلب إجازة لمدة 3 أيام', 'معلق'
where not exists (select 1 from public.pending_requests where company_id = 118 limit 1);

insert into public.events (company_id, name, description, event_datetime, location)
select 118, 'لقاء الموظفين الشهري', 'اجتماع دوري', '2026-06-15 10:00:00+00', 'قاعة الاجتماعات'
where not exists (select 1 from public.events where company_id = 118 limit 1);
