-- RBAC: standard roles + dynamic role_permissions (JSONB)

alter table public.employees
  drop constraint if exists employees_role_check;

update public.employees
set role = case
  when role in ('Admin', 'admin', 'مدير', 'مدير النظام') then 'Admin'
  when role in ('Executive', 'executive') then 'Executive'
  when role in ('HR_Manager', 'hr_manager', 'مدير موارد بشرية') then 'HR_Manager'
  when role in ('HR_Assistant', 'hr_assistant') then 'HR_Assistant'
  when role in ('Direct_Manager', 'direct_manager', 'مشرف') then 'Direct_Manager'
  when role in ('Employee', 'employee', 'موظف') then 'Employee'
  else coalesce(nullif(trim(role), ''), 'Employee')
end;

alter table public.employees
  add constraint employees_role_check
  check (
    role in (
      'Admin',
      'Executive',
      'HR_Manager',
      'HR_Assistant',
      'Direct_Manager',
      'Employee'
    )
  );

create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  role_name text not null,
  permissions jsonb not null default '{
    "can_edit_employees": false,
    "can_view_payroll": false,
    "can_create_events": false,
    "can_approve_financial": false,
    "can_approve_general": false
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, role_name),
  constraint role_permissions_role_name_check
    check (
      role_name in (
        'Executive',
        'HR_Manager',
        'HR_Assistant',
        'Direct_Manager'
      )
    )
);

create index if not exists role_permissions_company_id_idx
  on public.role_permissions (company_id);

alter table public.role_permissions enable row level security;

drop policy if exists exeer_all_select on public.role_permissions;
drop policy if exists exeer_all_insert on public.role_permissions;
drop policy if exists exeer_all_update on public.role_permissions;
drop policy if exists exeer_all_delete on public.role_permissions;

create policy exeer_all_select on public.role_permissions for select using (true);
create policy exeer_all_insert on public.role_permissions for insert with check (true);
create policy exeer_all_update on public.role_permissions for update using (true);
create policy exeer_all_delete on public.role_permissions for delete using (true);

-- Seed default permissions for existing companies (Admin configures via UI)
insert into public.role_permissions (company_id, role_name, permissions)
select
  c.id,
  seed.role_name,
  seed.permissions::jsonb
from public.companies c
cross join (
  values
    (
      'Executive',
      '{"can_edit_employees":true,"can_view_payroll":true,"can_create_events":true,"can_approve_financial":true,"can_approve_general":true}'
    ),
    (
      'HR_Manager',
      '{"can_edit_employees":true,"can_view_payroll":true,"can_create_events":true,"can_approve_financial":true,"can_approve_general":true}'
    ),
    (
      'HR_Assistant',
      '{"can_edit_employees":false,"can_view_payroll":false,"can_create_events":true,"can_approve_financial":false,"can_approve_general":true}'
    ),
    (
      'Direct_Manager',
      '{"can_edit_employees":false,"can_view_payroll":false,"can_create_events":false,"can_approve_financial":false,"can_approve_general":true}'
    )
) as seed(role_name, permissions)
on conflict (company_id, role_name) do nothing;
