-- Account deletion requests (processed manually or via scheduled job later)

create table if not exists public.account_deletion_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  requested_at timestamptz not null default now(),
  status text not null default 'pending',
  constraint account_deletion_requests_status_check check (
    status in ('pending', 'processing', 'completed', 'cancelled')
  )
);

create unique index if not exists account_deletion_requests_user_pending_idx
  on public.account_deletion_requests (user_id)
  where status = 'pending';

create index if not exists account_deletion_requests_status_requested_idx
  on public.account_deletion_requests (status, requested_at desc);

alter table public.account_deletion_requests enable row level security;

drop policy if exists account_deletion_requests_select_own on public.account_deletion_requests;
drop policy if exists account_deletion_requests_insert_own on public.account_deletion_requests;

create policy account_deletion_requests_select_own
  on public.account_deletion_requests for select to authenticated
  using (user_id = auth.uid());

create policy account_deletion_requests_insert_own
  on public.account_deletion_requests for insert to authenticated
  with check (user_id = auth.uid());
