-- Per-company key/value settings (feature flags and HR/payroll configuration)

create table if not exists public.company_settings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  setting_key text not null,
  setting_value jsonb not null default 'null'::jsonb,
  updated_by bigint references public.employees (id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint company_settings_company_key_unique unique (company_id, setting_key)
);

create index if not exists company_settings_company_id_idx
  on public.company_settings (company_id);

alter table public.company_settings enable row level security;

drop policy if exists company_settings_select on public.company_settings;
drop policy if exists company_settings_manage on public.company_settings;

create policy company_settings_select
  on public.company_settings for select to authenticated
  using (company_id = public.get_my_company_id());

create policy company_settings_manage
  on public.company_settings for all to authenticated
  using (
    company_id = public.get_my_company_id()
    and coalesce(public.get_my_role(), '') in ('owner', 'Admin')
  )
  with check (
    company_id = public.get_my_company_id()
    and coalesce(public.get_my_role(), '') in ('owner', 'Admin')
  );

grant all on table public.company_settings to authenticated, service_role;

notify pgrst, 'reload schema';
