-- Per-user quick sticky notes (dashboard)

create table if not exists public.user_quick_notes (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null default '',
  color text not null default 'amber',
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_quick_notes_user_unique unique (user_id),
  constraint user_quick_notes_color_check check (
    color in ('amber', 'mint', 'sky', 'rose')
  )
);

create index if not exists user_quick_notes_company_user_idx
  on public.user_quick_notes (company_id, user_id);

alter table public.user_quick_notes enable row level security;

drop policy if exists user_quick_notes_select_own on public.user_quick_notes;
drop policy if exists user_quick_notes_insert_own on public.user_quick_notes;
drop policy if exists user_quick_notes_update_own on public.user_quick_notes;
drop policy if exists user_quick_notes_delete_own on public.user_quick_notes;

create policy user_quick_notes_select_own
  on public.user_quick_notes for select to authenticated
  using (
    company_id = public.get_my_company_id()
    and user_id = auth.uid()
  );

create policy user_quick_notes_insert_own
  on public.user_quick_notes for insert to authenticated
  with check (
    company_id = public.get_my_company_id()
    and user_id = auth.uid()
  );

create policy user_quick_notes_update_own
  on public.user_quick_notes for update to authenticated
  using (
    company_id = public.get_my_company_id()
    and user_id = auth.uid()
  )
  with check (
    company_id = public.get_my_company_id()
    and user_id = auth.uid()
  );

create policy user_quick_notes_delete_own
  on public.user_quick_notes for delete to authenticated
  using (
    company_id = public.get_my_company_id()
    and user_id = auth.uid()
  );
