-- Smart goals archive (run after core schema)

create table if not exists public.smart_goals_archive (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  original_goal text not null,
  smart_goal_text text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists smart_goals_archive_company_id_idx
  on public.smart_goals_archive (company_id);

create index if not exists smart_goals_archive_company_created_idx
  on public.smart_goals_archive (company_id, created_at desc);

alter table public.smart_goals_archive enable row level security;

drop policy if exists exeer_all_select on public.smart_goals_archive;
drop policy if exists exeer_all_insert on public.smart_goals_archive;
drop policy if exists exeer_all_update on public.smart_goals_archive;
drop policy if exists exeer_all_delete on public.smart_goals_archive;

create policy exeer_all_select on public.smart_goals_archive
  for select using (true);

create policy exeer_all_insert on public.smart_goals_archive
  for insert with check (true);

create policy exeer_all_update on public.smart_goals_archive
  for update using (true);

create policy exeer_all_delete on public.smart_goals_archive
  for delete using (true);
