-- Smart interview archive (run after core schema)

create table if not exists public.interview_archive (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  job_title text not null,
  questions_text text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists interview_archive_company_id_idx
  on public.interview_archive (company_id);

create index if not exists interview_archive_company_created_idx
  on public.interview_archive (company_id, created_at desc);

alter table public.interview_archive enable row level security;

drop policy if exists exeer_all_select on public.interview_archive;
drop policy if exists exeer_all_insert on public.interview_archive;
drop policy if exists exeer_all_update on public.interview_archive;
drop policy if exists exeer_all_delete on public.interview_archive;

create policy exeer_all_select on public.interview_archive
  for select using (true);

create policy exeer_all_insert on public.interview_archive
  for insert with check (true);

create policy exeer_all_update on public.interview_archive
  for update using (true);

create policy exeer_all_delete on public.interview_archive
  for delete using (true);
