-- Performance Management: evaluation cycles, templates, employee evaluations

create table if not exists public.evaluation_cycles (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  name text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'Draft',
  created_at timestamptz not null default now(),
  constraint evaluation_cycles_status_check
    check (status in ('Draft', 'Active', 'Completed')),
  constraint evaluation_cycles_date_range_check
    check (end_date >= start_date)
);

create index if not exists evaluation_cycles_company_id_idx
  on public.evaluation_cycles (company_id);

create index if not exists evaluation_cycles_company_status_idx
  on public.evaluation_cycles (company_id, status);

create table if not exists public.evaluation_templates (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  created_at timestamptz not null default now()
);

create index if not exists evaluation_templates_category_idx
  on public.evaluation_templates (category);

create table if not exists public.employee_evaluations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  cycle_id bigint not null references public.evaluation_cycles (id) on delete cascade,
  evaluator_id bigint not null references public.employees (id) on delete cascade,
  evaluated_employee_id bigint not null references public.employees (id) on delete cascade,
  template_id bigint not null references public.evaluation_templates (id) on delete restrict,
  answers jsonb not null default '{}'::jsonb,
  score numeric,
  status text not null default 'Pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employee_evaluations_status_check
    check (status in ('Pending', 'Completed'))
);

create index if not exists employee_evaluations_company_id_idx
  on public.employee_evaluations (company_id);

create index if not exists employee_evaluations_cycle_id_idx
  on public.employee_evaluations (cycle_id);

create index if not exists employee_evaluations_evaluated_idx
  on public.employee_evaluations (evaluated_employee_id);

alter table public.evaluation_cycles enable row level security;
alter table public.evaluation_templates enable row level security;
alter table public.employee_evaluations enable row level security;

drop policy if exists exeer_all_select on public.evaluation_cycles;
drop policy if exists exeer_all_insert on public.evaluation_cycles;
drop policy if exists exeer_all_update on public.evaluation_cycles;
drop policy if exists exeer_all_delete on public.evaluation_cycles;

create policy exeer_all_select on public.evaluation_cycles for select using (true);
create policy exeer_all_insert on public.evaluation_cycles for insert with check (true);
create policy exeer_all_update on public.evaluation_cycles for update using (true);
create policy exeer_all_delete on public.evaluation_cycles for delete using (true);

drop policy if exists exeer_all_select on public.evaluation_templates;
drop policy if exists exeer_all_insert on public.evaluation_templates;
drop policy if exists exeer_all_update on public.evaluation_templates;
drop policy if exists exeer_all_delete on public.evaluation_templates;

create policy exeer_all_select on public.evaluation_templates for select using (true);
create policy exeer_all_insert on public.evaluation_templates for insert with check (true);
create policy exeer_all_update on public.evaluation_templates for update using (true);
create policy exeer_all_delete on public.evaluation_templates for delete using (true);

drop policy if exists exeer_all_select on public.employee_evaluations;
drop policy if exists exeer_all_insert on public.employee_evaluations;
drop policy if exists exeer_all_update on public.employee_evaluations;
drop policy if exists exeer_all_delete on public.employee_evaluations;

create policy exeer_all_select on public.employee_evaluations for select using (true);
create policy exeer_all_insert on public.employee_evaluations for insert with check (true);
create policy exeer_all_update on public.employee_evaluations for update using (true);
create policy exeer_all_delete on public.employee_evaluations for delete using (true);

-- Seed standard evaluation templates (global pillars)
insert into public.evaluation_templates (category, title)
select seed.category, seed.title
from (
  values
    ('القيادة والنضج المؤسسي', 'النضج المؤسسي'),
    ('القيادة والنضج المؤسسي', 'تقييم المدراء العام'),
    ('القيادة والنضج المؤسسي', 'تقييم المنشأة'),
    ('الانضباط والكفاءة التشغيلية', 'كفاءة خطوط الإنتاج'),
    ('الانضباط والكفاءة التشغيلية', 'كفاءة سلاسل الإمداد'),
    ('الانضباط والكفاءة التشغيلية', 'الكفاءة المالية'),
    ('الابتكار والجاهزية للمستقبل', 'جودة خدمات الموارد'),
    ('الابتكار والجاهزية للمستقبل', 'الجاهزية الرقمية'),
    ('الابتكار والجاهزية للمستقبل', 'الابتكار والارتباط')
) as seed(category, title)
where not exists (
  select 1 from public.evaluation_templates existing
  where existing.category = seed.category and existing.title = seed.title
);
