-- Employee achievements (run after core schema)

create table if not exists public.employee_achievements (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  employee_id bigint not null references public.employees (id) on delete cascade,
  title text not null,
  description text not null default '',
  achievement_date date not null,
  created_at timestamptz not null default now()
);

create index if not exists employee_achievements_company_id_idx
  on public.employee_achievements (company_id);

create index if not exists employee_achievements_employee_id_idx
  on public.employee_achievements (employee_id);

create index if not exists employee_achievements_company_date_idx
  on public.employee_achievements (company_id, achievement_date desc);

alter table public.employee_achievements enable row level security;

drop policy if exists exeer_all_select on public.employee_achievements;
drop policy if exists exeer_all_insert on public.employee_achievements;
drop policy if exists exeer_all_update on public.employee_achievements;
drop policy if exists exeer_all_delete on public.employee_achievements;

create policy exeer_all_select on public.employee_achievements
  for select using (true);

create policy exeer_all_insert on public.employee_achievements
  for insert with check (true);

create policy exeer_all_update on public.employee_achievements
  for update using (true);

create policy exeer_all_delete on public.employee_achievements
  for delete using (true);
