-- Industry context + reports archive + smart task rate-limit marker

alter table public.companies
  add column if not exists industry text not null default 'الخدمات العامة';

alter table public.tasks
  add column if not exists ai_source text;

create index if not exists tasks_company_ai_source_created_idx
  on public.tasks (company_id, ai_source, created_at desc)
  where ai_source is not null;

create table if not exists public.reports_archive (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  report_type text not null default 'Monthly',
  report_content text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists reports_archive_company_id_idx
  on public.reports_archive (company_id);

create index if not exists reports_archive_company_type_created_idx
  on public.reports_archive (company_id, report_type, created_at desc);

alter table public.reports_archive enable row level security;

drop policy if exists exeer_all_select on public.reports_archive;
drop policy if exists exeer_all_insert on public.reports_archive;
drop policy if exists exeer_all_update on public.reports_archive;
drop policy if exists exeer_all_delete on public.reports_archive;

create policy exeer_all_select on public.reports_archive
  for select using (true);

create policy exeer_all_insert on public.reports_archive
  for insert with check (true);

create policy exeer_all_update on public.reports_archive
  for update using (true);

create policy exeer_all_delete on public.reports_archive
  for delete using (true);

update public.companies
set industry = 'الخدمات العامة'
where industry is null or trim(industry) = '';
