-- Employee self-service requests + personal report archive support

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  employee_id bigint not null references public.employees (id) on delete cascade,
  request_type text not null,
  details text not null default '',
  amount numeric,
  installments integer,
  monthly_deduction numeric,
  attachment_url text,
  status text not null default 'Pending',
  routing_to text not null,
  created_at timestamptz not null default now(),
  constraint requests_request_type_check
    check (request_type in ('Financial', 'Leave', 'General')),
  constraint requests_routing_to_check
    check (routing_to in ('HR_Manager', 'Direct_Manager')),
  constraint requests_status_check
    check (status in ('Pending', 'Approved', 'Rejected', 'In_Review'))
);

create index if not exists requests_company_id_idx
  on public.requests (company_id);

create index if not exists requests_employee_id_idx
  on public.requests (employee_id);

create index if not exists requests_company_employee_created_idx
  on public.requests (company_id, employee_id, created_at desc);

alter table public.requests enable row level security;

drop policy if exists exeer_all_select on public.requests;
drop policy if exists exeer_all_insert on public.requests;
drop policy if exists exeer_all_update on public.requests;
drop policy if exists exeer_all_delete on public.requests;

create policy exeer_all_select on public.requests for select using (true);
create policy exeer_all_insert on public.requests for insert with check (true);
create policy exeer_all_update on public.requests for update using (true);
create policy exeer_all_delete on public.requests for delete using (true);

-- Per-employee personal mentor reports (rate limit: 1 / 28 days)
alter table public.reports_archive
  add column if not exists employee_id bigint references public.employees (id) on delete set null;

create index if not exists reports_archive_employee_type_created_idx
  on public.reports_archive (company_id, employee_id, report_type, created_at desc)
  where employee_id is not null;

-- Attachment storage bucket (1 MB enforced client-side)
insert into storage.buckets (id, name, public, file_size_limit)
values ('request-attachments', 'request-attachments', true, 1048576)
on conflict (id) do update
set file_size_limit = 1048576;

drop policy if exists request_attachments_select on storage.objects;
drop policy if exists request_attachments_insert on storage.objects;
drop policy if exists request_attachments_update on storage.objects;
drop policy if exists request_attachments_delete on storage.objects;

create policy request_attachments_select on storage.objects
  for select using (bucket_id = 'request-attachments');

create policy request_attachments_insert on storage.objects
  for insert with check (bucket_id = 'request-attachments');

create policy request_attachments_update on storage.objects
  for update using (bucket_id = 'request-attachments');

create policy request_attachments_delete on storage.objects
  for delete using (bucket_id = 'request-attachments');
