-- Per-employee quick sticky notes (dashboard)
-- Schema: id, company_id, employee_id, content, color, is_pinned, created_at, updated_at

create table if not exists public.user_quick_notes (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  employee_id bigint not null references public.employees (id) on delete cascade,
  content text not null default '',
  color text not null default 'amber',
  is_pinned boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_quick_notes_employee_unique unique (employee_id),
  constraint user_quick_notes_color_check check (
    color in ('amber', 'mint', 'sky', 'rose')
  )
);

create index if not exists user_quick_notes_company_employee_idx
  on public.user_quick_notes (company_id, employee_id);

alter table public.user_quick_notes enable row level security;

drop policy if exists user_quick_notes_select_own on public.user_quick_notes;
drop policy if exists user_quick_notes_insert_own on public.user_quick_notes;
drop policy if exists user_quick_notes_update_own on public.user_quick_notes;
drop policy if exists user_quick_notes_delete_own on public.user_quick_notes;

create policy user_quick_notes_select_own
  on public.user_quick_notes for select to authenticated
  using (
    company_id = public.get_my_company_id()
    and employee_id = public.get_my_employee_id()
  );

create policy user_quick_notes_insert_own
  on public.user_quick_notes for insert to authenticated
  with check (
    company_id = public.get_my_company_id()
    and employee_id = public.get_my_employee_id()
  );

create policy user_quick_notes_update_own
  on public.user_quick_notes for update to authenticated
  using (
    company_id = public.get_my_company_id()
    and employee_id = public.get_my_employee_id()
  )
  with check (
    company_id = public.get_my_company_id()
    and employee_id = public.get_my_employee_id()
  );

create policy user_quick_notes_delete_own
  on public.user_quick_notes for delete to authenticated
  using (
    company_id = public.get_my_company_id()
    and employee_id = public.get_my_employee_id()
  );
