-- User-created calendar appointments (company-scoped)

create table if not exists public.calendar_appointments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  created_by uuid references auth.users (id) on delete set null,
  title text not null,
  description text,
  appointment_date date not null,
  appointment_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists calendar_appointments_company_date_idx
  on public.calendar_appointments (company_id, appointment_date);

alter table public.calendar_appointments enable row level security;

drop policy if exists calendar_appointments_company_all on public.calendar_appointments;

create policy calendar_appointments_company_all
  on public.calendar_appointments for all to authenticated
  using (company_id = public.get_my_company_id())
  with check (company_id = public.get_my_company_id());
