-- Global HR reference lists (departments, job titles, leave types)

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint departments_name_unique unique (name)
);

create table if not exists public.job_titles (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint job_titles_name_unique unique (name)
);

create table if not exists public.leave_types (
  id bigint generated by default as identity primary key,
  name text not null,
  default_days integer not null default 0,
  created_at timestamptz not null default now(),
  constraint leave_types_name_unique unique (name)
);

create index if not exists departments_name_idx on public.departments (name);
create index if not exists job_titles_name_idx on public.job_titles (name);
create index if not exists leave_types_name_idx on public.leave_types (name);

alter table public.departments enable row level security;
alter table public.job_titles enable row level security;
alter table public.leave_types enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['departments', 'job_titles', 'leave_types']
  loop
    execute format('drop policy if exists exeer_all_select on public.%I', t);
    execute format('drop policy if exists exeer_all_insert on public.%I', t);
    execute format('drop policy if exists exeer_all_update on public.%I', t);
    execute format('drop policy if exists exeer_all_delete on public.%I', t);
    execute format(
      'create policy exeer_all_select on public.%I for select using (true)',
      t
    );
    execute format(
      'create policy exeer_all_insert on public.%I for insert with check (true)',
      t
    );
    execute format(
      'create policy exeer_all_update on public.%I for update using (true)',
      t
    );
    execute format(
      'create policy exeer_all_delete on public.%I for delete using (true)',
      t
    );
  end loop;
end $$;
